### ISSUE TITLE
ffmppeg ffmpy bug

### ISSUE THREAD

**Issue by gsgoldma** [fkunn1326/openpose-editor#58]
had to revert to an earlier commit for it work.  see here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8211

**Comment by fkunn1326** [comment]
Sorry, I'm not using ffmpy or ffmpeg in this repo and don't know the solution.
Can you send me a list of other extensions?

**Comment by nonnonstop** [comment]
This is because when you Send to txt2img in the OpenPose Editor, the pose file is also sent to ControlNet-M2M after commit 51e10e2d2afda45db00e6507d36678665bd75840.
The label "ControlNet-M2M" must be excluded.

![image](https://user-images.githubusercontent.com/42905588/222656730-115d9210-f22b-411e-be40-e85c1354d7af.png)

**Comment by JarringBye** [comment]
> 这是因为当您在 OpenPose Editor 中发送到 txt2img 时，姿势文件也会在提交[51e10e2](https://github.com/fkunn1326/openpose-editor/commit/51e10e2d2afda45db00e6507d36678665bd75840)后发送到 ControlNet-M2M 。 必须排除标签“ControlNet-M2M”。
> 
> ![图像](https://user-images.githubusercontent.com/42905588/222656730-115d9210-f22b-411e-be40-e85c1354d7af.png)

good hope merge
